<?php

namespace ContainerIS9uG49;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EGg1Z7tService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eGg1Z7t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eGg1Z7t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'generatorService' => ['privates', 'App\\Service\\PdfGeneratorService', 'getPdfGeneratorServiceService', true],
        ], [
            'generatorService' => 'App\\Service\\PdfGeneratorService',
        ]);
    }
}
