<?php

namespace ContainerJd0xbJr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdministratifControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AdministratifController' shared autowired service.
     *
     * @return \App\Controller\AdministratifController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/AdministratifController.php';

        $container->services['App\\Controller\\AdministratifController'] = $instance = new \App\Controller\AdministratifController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\AdministratifController', $container));

        return $instance;
    }
}
