<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJd0xbJr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJd0xbJr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJd0xbJr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJd0xbJr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJd0xbJr\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jd0xbJr',
    'container.build_id' => '924ad36c',
    'container.build_time' => 1645270935,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJd0xbJr');
