<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIS9uG49\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIS9uG49/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIS9uG49.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIS9uG49\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIS9uG49\App_KernelDevDebugContainer([
    'container.build_hash' => 'IS9uG49',
    'container.build_id' => 'b0f5e9ed',
    'container.build_time' => 1645226568,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIS9uG49');
