<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1v8xZVN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1v8xZVN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1v8xZVN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1v8xZVN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1v8xZVN\App_KernelDevDebugContainer([
    'container.build_hash' => '1v8xZVN',
    'container.build_id' => '4aa9274f',
    'container.build_time' => 1645060957,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1v8xZVN');
